//! The transport of RFC 8999, 9000, 9001 and 9002. Knows nothing about HTTP (decision 5,
//! invariant 26), which build/modules.zig enforces and tools/graph_check.zig proves.
const std = @import("std");

pub const core = @import("core");
pub const wire = @import("wire");
pub const crypto = @import("crypto");
pub const tls = @import("tls");
pub const constants = @import("constants.zig");
pub const packet = @import("packet/packet.zig");
pub const frame = @import("frame/frame.zig");
pub const frame_ack = @import("frame/frame_ack.zig");
pub const space = @import("space/space.zig");
pub const termination = @import("termination.zig");
pub const error_code = @import("error_code.zig");
pub const flow = @import("flow.zig");
pub const connection_id = @import("connection_id.zig");
pub const path = @import("path.zig");
pub const stateless_reset = @import("stateless_reset.zig");
pub const rtt = @import("rtt.zig");
pub const recovery_sent = @import("recovery/recovery_sent.zig");
pub const recovery_loss = @import("recovery/recovery_loss.zig");
pub const recovery_congestion = @import("recovery/recovery_congestion.zig");
pub const recovery_timer = @import("recovery/recovery_timer.zig");
pub const recovery_pacing = @import("recovery/recovery_pacing.zig");
pub const recovery = @import("recovery/recovery.zig");
pub const recovery_ack = @import("recovery/recovery_ack.zig");
pub const stream = @import("stream/stream.zig");
pub const connection = @import("connection/connection.zig");
pub const connection_identity = @import("connection/connection_identity.zig");
pub const connection_keys = @import("connection/connection_keys.zig");
pub const connection_receive = @import("connection/connection_receive.zig");
pub const connection_frames = @import("connection/connection_frames.zig");
pub const connection_stream_frames = @import("connection/connection_stream_frames.zig");
pub const connection_path_frames = @import("connection/connection_path_frames.zig");
pub const Connection = connection.Connection;
pub const crypto_stream = @import("crypto_stream.zig");
pub const transport_parameters = @import("transport_parameters.zig");
pub const transport_parameters_read = @import("transport_parameters_read.zig");

test {
    std.testing.refAllDecls(@This());
    _ = constants;
    _ = packet;
    _ = frame;
    _ = frame_ack;
    _ = space;
    _ = termination;
    _ = error_code;
    _ = flow;
    _ = connection_id;
    _ = path;
    _ = stateless_reset;
    _ = rtt;
    _ = recovery_sent;
    _ = recovery_loss;
    _ = recovery_congestion;
    _ = recovery_timer;
    _ = recovery_pacing;
    _ = recovery;
    _ = recovery_ack;
    _ = stream;
    _ = connection;
    _ = connection_identity;
    _ = connection_keys;
    _ = connection_receive;
    _ = connection_frames;
    _ = connection_stream_frames;
    _ = connection_path_frames;
    _ = crypto_stream;
    _ = transport_parameters;
    _ = transport_parameters_read;
}
