import Colibri.Qpack.InsertCount
import Colibri.Qpack.Index

/-!
# Vectors from the proved definitions

Writes, or checks, the outputs of the definitions `Colibri/` proves over a range of inputs, into
files beside the Zig functions they mirror. A Zig unit test requires the Zig function to give the
same outputs, which is what ties a proof about a Lean function to the Zig code (decision 77).

    lake exe vectors (--write | --check) <src/qpack directory>
-/
open Colibri.Qpack

/-- The largest `MaxEntries` the Required Insert Count vectors cover, every smaller one included. -/
def maxEntriesLimit : Nat := 8

/-- Every encoded value, insert count and `MaxEntries` in range, and what `decode` answers:
`encoded total max_entries required`, with `error` for none. -/
def insertCountLines : Array String := Id.run do
  let mut lines := #["# encoded total max_entries required, from spec/lean/Colibri/Qpack/InsertCount.lean. Generated by spec/lean/Vectors.lean; do not edit."]
  for maxEntries in List.range (maxEntriesLimit + 1) do
    for total in List.range (4 * maxEntries + 3) do
      for encoded in List.range (2 * maxEntries + 3) do
        let answer := match InsertCount.decode encoded total maxEntries with
          | some required => toString required
          | none => "error"
        lines := lines.push s!"{encoded} {total} {maxEntries} {answer}"
  return lines

/-- The largest Required Insert Count and Delta Base the Base vectors cover. -/
def baseLimit : Nat := 8

/-- Every Required Insert Count, Sign bit and Delta Base in range, and what `decodeBase` answers:
`required sign delta base`, with `error` for none. -/
def baseLines : Array String := Id.run do
  let mut lines := #["# required sign delta base, from spec/lean/Colibri/Qpack/Index.lean. Generated by spec/lean/Vectors.lean; do not edit."]
  for required in List.range (baseLimit + 1) do
    for sign in [false, true] do
      for delta in List.range (baseLimit + 1) do
        let answer := match Index.decodeBase required sign delta with
          | some base => toString base
          | none => "error"
        lines := lines.push s!"{required} {if sign then 1 else 0} {delta} {answer}"
  return lines

def files : List (String × Array String) :=
  [("insert_count_vectors.txt", insertCountLines), ("base_vectors.txt", baseLines)]

def render (lines : Array String) : String :=
  String.intercalate "\n" lines.toList ++ "\n"

def main (args : List String) : IO UInt32 := do
  match args with
  | ["--write", directory] =>
    for (name, lines) in files do
      IO.FS.writeFile (directory ++ "/" ++ name) (render lines)
    return 0
  | ["--check", directory] =>
    let mut status : UInt32 := 0
    for (name, lines) in files do
      let path := directory ++ "/" ++ name
      let committed ← IO.FS.readFile path
      if committed != render lines then
        IO.eprintln s!"vectors: {path} differs from what spec/lean's definitions give; run `zig build lean -- write`"
        status := 1
    return status
  | _ =>
    IO.eprintln "usage: vectors (--write | --check) <src/qpack directory>"
    return 2
