import Colibri.Qpack.InsertCount
import Colibri.Qpack.Index
import Colibri.Wire.Varint
import Colibri.Wire.PrefixedInteger
import Colibri.Wire.Huffman
import Colibri.Quic.PacketNumber
import Colibri.Quic.AckRanges

/-!
# Vectors from the proved definitions

Writes, or checks, the outputs of the definitions `Colibri/` proves over a range of inputs, into
files beside the Zig functions they mirror. A Zig unit test requires the Zig function to give the
same outputs, which is what ties a proof about a Lean function to the Zig code (decision 77).

    lake exe vectors (--write | --check) <src directory>
-/
open Colibri.Qpack
open Colibri.Wire
open Colibri.Quic

/-- The largest `MaxEntries` the Required Insert Count vectors cover, every smaller one included. -/
def maxEntriesLimit : Nat := 8

/-- Every encoded value, insert count and `MaxEntries` in range, and what `decode` answers:
`encoded total max_entries required`, with `error` for none. -/
def insertCountLines : Array String := Id.run do
  let mut lines := #["# encoded total max_entries required, from spec/lean/Colibri/Qpack/InsertCount.lean. Generated by spec/lean/Vectors.lean; do not edit."]
  for maxEntries in List.range (maxEntriesLimit + 1) do
    for total in List.range (4 * maxEntries + 3) do
      for encoded in List.range (2 * maxEntries + 3) do
        let answer := match InsertCount.decode encoded total maxEntries with
          | some required => toString required
          | none => "error"
        lines := lines.push s!"{encoded} {total} {maxEntries} {answer}"
  return lines

/-- The largest Required Insert Count and Delta Base the Base vectors cover. -/
def baseLimit : Nat := 8

/-- Every Required Insert Count, Sign bit and Delta Base in range, and what `decodeBase` answers:
`required sign delta base`, with `error` for none. -/
def baseLines : Array String := Id.run do
  let mut lines := #["# required sign delta base, from spec/lean/Colibri/Qpack/Index.lean. Generated by spec/lean/Vectors.lean; do not edit."]
  for required in List.range (baseLimit + 1) do
    for sign in [false, true] do
      for delta in List.range (baseLimit + 1) do
        let answer := match Index.decodeBase required sign delta with
          | some base => toString base
          | none => "error"
        lines := lines.push s!"{required} {if sign then 1 else 0} {delta} {answer}"
  return lines

/-- The values the varint vectors cover: each boundary of RFC 9000 §16's four lengths, one past it
and one before it, and the examples of RFC 9000 Appendix A.1. -/
def varintValues : List Nat :=
  [0, 1, 2, 37, 62, 63, 64, 65, 151, 1000, 15293, 16382, 16383, 16384, 16385,
    2 ^ 30 - 2, 2 ^ 30 - 1, 2 ^ 30, 2 ^ 30 + 1, 494878333, 151288809941952652,
    2 ^ 62 - 2, 2 ^ 62 - 1]

/-- One octet as two lowercase hex digits. -/
def hexOctet (n : Nat) : String :=
  let digits := Nat.toDigits 16 n
  String.ofList (if digits.length < 2 then '0' :: digits else digits)

def hex (octets : List Nat) : String := String.join (octets.map hexOctet)

/-- What `Varint.decode` answers for `octets`: `value len`, or `error`. -/
def decodeAnswer (octets : List Nat) : String :=
  match Varint.decode octets with
  | some (value, len) => s!"{value} {len}"
  | none => "error"

/-- `encode value len octets` for each value in each length that carries it; `decode octets answer`
for every one-octet input and every proper prefix of those encodings; and `minimal value len`. -/
def varintLines : Array String := Id.run do
  let mut lines := #["# encode value len octets | decode octets (value len | error) | minimal value len, from spec/lean/Colibri/Wire/Varint.lean. Generated by spec/lean/Vectors.lean; do not edit."]
  for tag in List.range 4 do
    for value in varintValues do
      if value ≤ Varint.valueMax (2 ^ tag) then
        let octets := Varint.encodeWithTag value tag
        lines := lines.push s!"encode {value} {2 ^ tag} {hex octets}"
        for cut in List.range octets.length do
          if cut > 0 then
            lines := lines.push s!"decode {hex (octets.take cut)} {decodeAnswer (octets.take cut)}"
  for first in List.range 256 do
    lines := lines.push s!"decode {hex [first]} {decodeAnswer [first]}"
  for value in varintValues do
    lines := lines.push s!"minimal {value} {Varint.encodedLenMinimal value}"
  return lines

/-- The values the prefixed integer vectors cover at prefix size `n`: each side of the prefix's
largest value, of one and two continuation octets, RFC 7541 Appendix C.1's 10, 1337 and 42, and
the 62-bit ceiling. -/
def prefixedValues (n : Nat) : List Nat :=
  let m := PrefixedInteger.prefixMax n
  [0, 1, 10, 42, m - 1, m, m + 1, m + 127, m + 128, m + 16383, m + 16384, 1337, 2 ^ 62 - 1].eraseDups

/-- What `decodeLimited` answers: `value len`, or the error `prefixed_integer.zig` names. -/
def outcomeText : PrefixedInteger.Outcome → String
  | .value v len => s!"{v} {len}"
  | .truncated => "truncated"
  | .tooLong => "too_long"
  | .tooLarge => "too_large"

/-- For each prefix size 1 to 8 and each value, with no high bits and with every high bit set:
`encode n high value octets`, then `decode n octets outcome` for each proper prefix. Then, per
size, the inputs only colibri's limits refuse: a tenth continuation octet, flagged or ending the
integer, and 2^62. -/
def prefixedIntegerLines : Array String := Id.run do
  let mut lines := #["# encode n high value octets | decode n octets (value len | truncated | too_long | too_large), from spec/lean/Colibri/Wire/PrefixedInteger.lean. Generated by spec/lean/Vectors.lean; do not edit."]
  for size in List.range 8 do
    let n := size + 1
    for high in [0, 256 - 2 ^ n].eraseDups do
      for value in prefixedValues n do
        let octets := PrefixedInteger.encode n high value
        lines := lines.push s!"encode {n} {high} {value} {hex octets}"
        for cut in List.range octets.length do
          if cut > 0 then
            lines := lines.push s!"decode {n} {hex (octets.take cut)} {outcomeText (PrefixedInteger.decodeLimited n (octets.take cut))}"
    let tooLong := PrefixedInteger.prefixMax n :: List.replicate 10 128
    lines := lines.push s!"decode {n} {hex tooLong} {outcomeText (PrefixedInteger.decodeLimited n tooLong)}"
    -- A tenth continuation octet that would end the integer is still one past the limit.
    let tooLongEnding := PrefixedInteger.prefixMax n :: (List.replicate 9 128 ++ [0])
    lines := lines.push s!"decode {n} {hex tooLongEnding} {outcomeText (PrefixedInteger.decodeLimited n tooLongEnding)}"
    let tooLarge := PrefixedInteger.encode n 0 (2 ^ 62)
    lines := lines.push s!"decode {n} {hex tooLarge} {outcomeText (PrefixedInteger.decodeLimited n tooLarge)}"
  return lines

/-- An optional packet number as the vectors write it: `-` for none. -/
def optionText : Option Nat → String
  | some n => toString n
  | none => "-"

/-- The packet numbers sent before any acknowledgment: each side of the largest each length
carries, and the last packet number. -/
def unacknowledgedFulls : List Nat :=
  [0, 1, 126, 127, 128, 32766, 32767, 32768, 2 ^ 23 - 2, 2 ^ 23 - 1, 2 ^ 23, 2 ^ 31 - 2,
    2 ^ 31 - 1, 2 ^ 31, PacketNumber.numberMax]

/-- The largest numbers acknowledged, RFC 9000 Appendix A.2's among them. -/
def acknowledgedNumbers : List Nat :=
  [0, 1, 0xfe, 0xffff, 0xabe8b3, 0xa82f30ea, 2 ^ 33, PacketNumber.numberMax - 2 ^ 31,
    PacketNumber.numberMax - 1]

/-- The distances past the number acknowledged: each side of the largest each length carries,
and RFC 9000 Appendix A.2's two. -/
def sendDistances : List Nat :=
  [1, 2, 127, 128, 0x7fff, 0x8000, 0x7fffff, 0x800000, 0x7fffffff, 0x80000000,
    0xac5c02 - 0xabe8b3, 0xace8fe - 0xabe8b3]

/-- What `PacketNumber.encode` answers: the field's octets, or the error `packet_number.zig`
names. -/
def encodeText (full : Nat) (acked : Option Nat) : String :=
  match PacketNumber.encode full acked with
  | some (value, len) => hex (PacketNumber.field value len)
  | none => "range_too_large"

/-- `encode full acked octets` for every number sent with no acknowledgment, and for every
distance past each number acknowledged that stays a packet number. -/
def packetNumberEncodeLines : Array String := Id.run do
  let mut lines := #["# encode full acked (octets | range_too_large), acked - for none, from spec/lean/Colibri/Quic/PacketNumber.lean. Generated by spec/lean/Vectors.lean; do not edit."]
  for full in unacknowledgedFulls do
    lines := lines.push s!"encode {full} - {encodeText full none}"
  for acked in acknowledgedNumbers do
    for distance in sendDistances do
      let full := acked + distance
      if full ≤ PacketNumber.numberMax then
        lines := lines.push s!"encode {full} {acked} {encodeText full (some acked)}"
  return lines

/-- The largest numbers processed that the decode vectors cover at `len` octets: each side of the
first window's middle and end, RFC 9000 Appendix A.3's, and each side of the last window. -/
def processedNumbers (len : Nat) : List (Option Nat) :=
  let w := PacketNumber.window len
  let m := PacketNumber.numberMax
  [none, some 0, some 1, some (w / 2 - 2), some (w / 2 - 1), some (w - 2), some (w - 1), some w,
    some 0xa82f30ea, some (2 ^ 40), some (m - w), some (m - w / 2), some (m - 1), some m].eraseDups

/-- The fields the decode vectors cover past `largest`: the first and last of the window, and
each side of half a window above and below the number expected. -/
def fieldValues (largest : Option Nat) (len : Nat) : List Nat :=
  let w := PacketNumber.window len
  let h := w / 2
  let e := PacketNumber.expected largest
  ([0, 1, w - 1] ++ [0, 1, h - 1, h, h + 1, w - h - 1, w - h, w - h + 1, w - 1].map
    (fun k => (e + k) % w)).eraseDups

/-- `decode largest len value number`, largest - for none, for every field above at every
length, and RFC 9000 Appendix A.3's sample. -/
def packetNumberDecodeLines : Array String := Id.run do
  let mut lines := #["# decode largest len value number, largest - for none, from spec/lean/Colibri/Quic/PacketNumber.lean. Generated by spec/lean/Vectors.lean; do not edit."]
  lines := lines.push s!"decode {0xa82f30ea} 2 {0x9b32} {PacketNumber.decode (some 0xa82f30ea) 0x9b32 2}"
  for len in [1, 2, 3, 4] do
    for largest in processedNumbers len do
      for value in fieldValues largest len do
        lines := lines.push s!"decode {optionText largest} {len} {value} {PacketNumber.decode largest value len}"
  return lines

/-- Gap and ACK Range Length pairs as the vectors write them: `gap/length` joined by commas, or
`-` for none. -/
def pairsText (pairs : List (Nat × Nat)) : String :=
  if pairs.isEmpty then "-" else ",".intercalate (pairs.map fun (gap, length) => s!"{gap}/{length}")

/-- Ranges as the vectors write them: `smallest..largest` joined by commas. -/
def rangesText (ranges : List AckRanges.Range) : String :=
  ",".intercalate (ranges.map fun range => s!"{range.smallest}..{range.largest}")

/-- The Largest Acknowledged values the ACK range vectors cover. -/
def ackLargests : List Nat := [0, 1, 2, 3, 5, 1000, 2 ^ 62 - 1]

/-- The First ACK Range values at each edge of `largest`, below the varint ceiling. -/
def ackFirsts (largest : Nat) : List Nat :=
  ([0, 1, largest - 1, largest, largest + 1].filter (· ≤ 2 ^ 62 - 1)).eraseDups

/-- Pairs at each edge below `previous`: no gap, the gap that puts the next range's largest at 0,
and one more; each with no length, a length of one, the length that reaches 0, and one more. -/
def ackPairs (previous : Nat) : List (Nat × Nat) :=
  ([0, previous - 2, previous - 1].eraseDups.flatMap fun gap =>
    let largest := previous - gap - 2
    [0, 1, largest, largest + 1].eraseDups.map fun length => (gap, length)).eraseDups

/-- A second pair below `previous`: no gap, and each edge of reaching 0. -/
def ackEnds (previous : Nat) : List (Nat × Nat) :=
  [(0, 0), (previous - 2, 0), (previous - 2, 1), (previous - 1, 0)].eraseDups

/-- The pair lists for one frame: none, each of `ackPairs`, and each accepted one followed by
each of `ackEnds`. -/
def ackPairLists (largest first : Nat) : List (List (Nat × Nat)) :=
  if first > largest then [[], [(0, 0)]]
  else
    let previous := largest - first
    let singles := ackPairs previous
    let doubles := singles.flatMap fun pair =>
      match AckRanges.walk previous [pair] with
      | some [range] => (ackEnds range.smallest).map fun next => [pair, next]
      | _ => []
    [[]] ++ singles.map (fun pair => [pair]) ++ doubles

/-- Frames of 32 ranges, `ack_ranges_max` in `constants.zig`: one at the varint ceiling, one of
two numbers each, one that reaches 0 with its last range, and one whose last range goes one below
it. -/
def ackLongFrames : List (Nat × Nat × List (Nat × Nat)) :=
  [(2 ^ 62 - 1, 0, List.replicate 31 (0, 0)), (1000, 1, List.replicate 31 (1, 1)),
    (62, 0, List.replicate 31 (0, 0)), (61, 0, List.replicate 31 (0, 0))]

def ackFrames : List (Nat × Nat × List (Nat × Nat)) :=
  (ackLargests.flatMap fun largest => (ackFirsts largest).flatMap fun first =>
    (ackPairLists largest first).map fun pairs => (largest, first, pairs)) ++ ackLongFrames

/-- `decode largest first pairs answer` for every frame above, with the ranges or `below_zero`. -/
def ackDecodeLines : Array String := Id.run do
  let mut lines := #["# decode largest first (gap/length,... | -) (smallest..largest,... | below_zero), from spec/lean/Colibri/Quic/AckRanges.lean. Generated by spec/lean/Vectors.lean; do not edit."]
  for (largest, first, pairs) in ackFrames do
    let answer := match AckRanges.decode largest first pairs with
      | some ranges => rangesText ranges
      | none => "below_zero"
    lines := lines.push s!"decode {largest} {first} {pairsText pairs} {answer}"
  return lines

/-- `encode ranges largest first pairs` for every distinct set of ranges `decode` accepts above. -/
def ackEncodeLines : Array String := Id.run do
  let mut lines := #["# encode (smallest..largest,...) largest first (gap/length,... | -), from spec/lean/Colibri/Quic/AckRanges.lean. Generated by spec/lean/Vectors.lean; do not edit."]
  let accepted := (ackFrames.filterMap fun (largest, first, pairs) =>
    AckRanges.decode largest first pairs).eraseDups
  for ranges in accepted do
    if let some (largest, first, pairs) := AckRanges.encode ranges then
      lines := lines.push s!"encode {rangesText ranges} {largest} {first} {pairsText pairs}"
  return lines

/-- Octets as the Huffman vectors write them: hex, or `-` for none. -/
def hexOrDash (octets : List Nat) : String := if octets.isEmpty then "-" else hex octets

/-- A string's octets. -/
def octetsOf (text : String) : List Nat := text.toUTF8.toList.map (·.toNat)

/-- What `Huffman.decode` answers: the octets, or the error `huffman.zig` names. -/
def huffmanOutcomeText : Huffman.Outcome → String
  | .octets octets => hexOrDash octets
  | .eosInData => "eos_in_data"
  | .paddingTooLong => "padding_too_long"
  | .paddingNotEos => "padding_not_eos"

/-- The strings the encode vectors cover beside every single octet: none, the strings of RFC 7541
Appendix C.4 and C.6, octets 204 and 22, whose codes meet in a run of thirty-four ones, and all 256
octets in order. -/
def huffmanStrings : List (List Nat) :=
  [[]] ++ (["www.example.com", "no-cache", "custom-key", "custom-value", "302", "private",
    "Mon, 21 Oct 2013 20:13:21 GMT", "https://www.example.com", "307",
    "Mon, 21 Oct 2013 20:13:22 GMT", "gzip",
    "foo=ASDJKHQKBZXOQWEOPIUAXQWEOIU; max-age=3600; version=1"].map octetsOf) ++
  [[204, 22], List.range 256]

/-- The inputs the decode vectors cover: every one octet, every two octets starting 0x00, 0x7f,
0xfe or 0xff, and one to five octets of ones, whose thirty ones make EOS. -/
def huffmanInputs : List (List Nat) :=
  (List.range 256).map (fun octet => [octet]) ++
  ([0x00, 0x7f, 0xfe, 0xff].flatMap fun first => (List.range 256).map fun second => [first, second]) ++
  ((List.range 5).map fun count => List.replicate (count + 1) 0xff) ++
  [[0xff, 0xff, 0xff, 0xfc], [0xff, 0xff, 0xff, 0xfd], [0xff, 0xff, 0xff, 0xfe]]

/-- `code symbol code bits` for every row of the table; `encode octets encoded` for each string
above and each single octet; `decode encoded outcome` for each input above. -/
def huffmanLines : Array String := Id.run do
  let mut lines := #["# code symbol code bits | encode (octets | -) (encoded | -) | decode encoded (octets | - | eos_in_data | padding_too_long | padding_not_eos), from spec/lean/Colibri/Wire/Huffman.lean. Generated by spec/lean/Vectors.lean; do not edit."]
  for (row, symbol) in Huffman.codes.zip (List.range 257) do
    lines := lines.push s!"code {symbol} {row.1} {row.2}"
  for octets in huffmanStrings ++ (List.range 256).map (fun octet => [octet]) do
    lines := lines.push s!"encode {hexOrDash octets} {hexOrDash (Huffman.encode octets)}"
  for encoded in huffmanInputs do
    lines := lines.push s!"decode {hex encoded} {huffmanOutcomeText (Huffman.decode encoded)}"
  return lines

def files : List (String × Array String) :=
  [("qpack/insert_count_vectors.txt", insertCountLines), ("qpack/base_vectors.txt", baseLines),
    ("wire/varint_vectors.txt", varintLines), ("wire/prefixed_integer_vectors.txt", prefixedIntegerLines),
    ("wire/huffman_vectors.txt", huffmanLines),
    ("quic/packet/packet_number_vectors.txt", packetNumberEncodeLines),
    ("crypto/packet_number_vectors.txt", packetNumberDecodeLines),
    ("quic/frame/frame_ack_vectors.txt", ackDecodeLines),
    ("quic/space/space_ack_vectors.txt", ackEncodeLines)]

def render (lines : Array String) : String :=
  String.intercalate "\n" lines.toList ++ "\n"

def main (args : List String) : IO UInt32 := do
  match args with
  | ["--write", directory] =>
    for (name, lines) in files do
      IO.FS.writeFile (directory ++ "/" ++ name) (render lines)
    return 0
  | ["--check", directory] =>
    let mut status : UInt32 := 0
    for (name, lines) in files do
      let path := directory ++ "/" ++ name
      let committed ← IO.FS.readFile path
      if committed != render lines then
        IO.eprintln s!"vectors: {path} differs from what spec/lean's definitions give; run `zig build lean -- write`"
        status := 1
    return status
  | _ =>
    IO.eprintln "usage: vectors (--write | --check) <src directory>"
    return 2
