import Colibri.Qpack.InsertCount
import Colibri.Qpack.Index
import Colibri.Wire.Varint
import Colibri.Wire.PrefixedInteger

/-!
# Vectors from the proved definitions

Writes, or checks, the outputs of the definitions `Colibri/` proves over a range of inputs, into
files beside the Zig functions they mirror. A Zig unit test requires the Zig function to give the
same outputs, which is what ties a proof about a Lean function to the Zig code (decision 77).

    lake exe vectors (--write | --check) <src directory>
-/
open Colibri.Qpack
open Colibri.Wire

/-- The largest `MaxEntries` the Required Insert Count vectors cover, every smaller one included. -/
def maxEntriesLimit : Nat := 8

/-- Every encoded value, insert count and `MaxEntries` in range, and what `decode` answers:
`encoded total max_entries required`, with `error` for none. -/
def insertCountLines : Array String := Id.run do
  let mut lines := #["# encoded total max_entries required, from spec/lean/Colibri/Qpack/InsertCount.lean. Generated by spec/lean/Vectors.lean; do not edit."]
  for maxEntries in List.range (maxEntriesLimit + 1) do
    for total in List.range (4 * maxEntries + 3) do
      for encoded in List.range (2 * maxEntries + 3) do
        let answer := match InsertCount.decode encoded total maxEntries with
          | some required => toString required
          | none => "error"
        lines := lines.push s!"{encoded} {total} {maxEntries} {answer}"
  return lines

/-- The largest Required Insert Count and Delta Base the Base vectors cover. -/
def baseLimit : Nat := 8

/-- Every Required Insert Count, Sign bit and Delta Base in range, and what `decodeBase` answers:
`required sign delta base`, with `error` for none. -/
def baseLines : Array String := Id.run do
  let mut lines := #["# required sign delta base, from spec/lean/Colibri/Qpack/Index.lean. Generated by spec/lean/Vectors.lean; do not edit."]
  for required in List.range (baseLimit + 1) do
    for sign in [false, true] do
      for delta in List.range (baseLimit + 1) do
        let answer := match Index.decodeBase required sign delta with
          | some base => toString base
          | none => "error"
        lines := lines.push s!"{required} {if sign then 1 else 0} {delta} {answer}"
  return lines

/-- The values the varint vectors cover: each boundary of RFC 9000 §16's four lengths, one past it
and one before it, and the examples of RFC 9000 Appendix A.1. -/
def varintValues : List Nat :=
  [0, 1, 2, 37, 62, 63, 64, 65, 151, 1000, 15293, 16382, 16383, 16384, 16385,
    2 ^ 30 - 2, 2 ^ 30 - 1, 2 ^ 30, 2 ^ 30 + 1, 494878333, 151288809941952652,
    2 ^ 62 - 2, 2 ^ 62 - 1]

/-- One octet as two lowercase hex digits. -/
def hexOctet (n : Nat) : String :=
  let digits := Nat.toDigits 16 n
  String.ofList (if digits.length < 2 then '0' :: digits else digits)

def hex (octets : List Nat) : String := String.join (octets.map hexOctet)

/-- What `Varint.decode` answers for `octets`: `value len`, or `error`. -/
def decodeAnswer (octets : List Nat) : String :=
  match Varint.decode octets with
  | some (value, len) => s!"{value} {len}"
  | none => "error"

/-- `encode value len octets` for each value in each length that carries it; `decode octets answer`
for every one-octet input and every proper prefix of those encodings; and `minimal value len`. -/
def varintLines : Array String := Id.run do
  let mut lines := #["# encode value len octets | decode octets (value len | error) | minimal value len, from spec/lean/Colibri/Wire/Varint.lean. Generated by spec/lean/Vectors.lean; do not edit."]
  for tag in List.range 4 do
    for value in varintValues do
      if value ≤ Varint.valueMax (2 ^ tag) then
        let octets := Varint.encodeWithTag value tag
        lines := lines.push s!"encode {value} {2 ^ tag} {hex octets}"
        for cut in List.range octets.length do
          if cut > 0 then
            lines := lines.push s!"decode {hex (octets.take cut)} {decodeAnswer (octets.take cut)}"
  for first in List.range 256 do
    lines := lines.push s!"decode {hex [first]} {decodeAnswer [first]}"
  for value in varintValues do
    lines := lines.push s!"minimal {value} {Varint.encodedLenMinimal value}"
  return lines

/-- The values the prefixed integer vectors cover at prefix size `n`: each side of the prefix's
largest value, of one and two continuation octets, RFC 7541 Appendix C.1's 10, 1337 and 42, and
the 62-bit ceiling. -/
def prefixedValues (n : Nat) : List Nat :=
  let m := PrefixedInteger.prefixMax n
  [0, 1, 10, 42, m - 1, m, m + 1, m + 127, m + 128, m + 16383, m + 16384, 1337, 2 ^ 62 - 1].eraseDups

/-- What `decodeLimited` answers: `value len`, or the error `prefixed_integer.zig` names. -/
def outcomeText : PrefixedInteger.Outcome → String
  | .value v len => s!"{v} {len}"
  | .truncated => "truncated"
  | .tooLong => "too_long"
  | .tooLarge => "too_large"

/-- For each prefix size 1 to 8 and each value, with no high bits and with every high bit set:
`encode n high value octets`, then `decode n octets outcome` for each proper prefix. Then, per
size, the inputs only colibri's limits refuse: a tenth continuation octet, flagged or ending the
integer, and 2^62. -/
def prefixedIntegerLines : Array String := Id.run do
  let mut lines := #["# encode n high value octets | decode n octets (value len | truncated | too_long | too_large), from spec/lean/Colibri/Wire/PrefixedInteger.lean. Generated by spec/lean/Vectors.lean; do not edit."]
  for size in List.range 8 do
    let n := size + 1
    for high in [0, 256 - 2 ^ n].eraseDups do
      for value in prefixedValues n do
        let octets := PrefixedInteger.encode n high value
        lines := lines.push s!"encode {n} {high} {value} {hex octets}"
        for cut in List.range octets.length do
          if cut > 0 then
            lines := lines.push s!"decode {n} {hex (octets.take cut)} {outcomeText (PrefixedInteger.decodeLimited n (octets.take cut))}"
    let tooLong := PrefixedInteger.prefixMax n :: List.replicate 10 128
    lines := lines.push s!"decode {n} {hex tooLong} {outcomeText (PrefixedInteger.decodeLimited n tooLong)}"
    -- A tenth continuation octet that would end the integer is still one past the limit.
    let tooLongEnding := PrefixedInteger.prefixMax n :: (List.replicate 9 128 ++ [0])
    lines := lines.push s!"decode {n} {hex tooLongEnding} {outcomeText (PrefixedInteger.decodeLimited n tooLongEnding)}"
    let tooLarge := PrefixedInteger.encode n 0 (2 ^ 62)
    lines := lines.push s!"decode {n} {hex tooLarge} {outcomeText (PrefixedInteger.decodeLimited n tooLarge)}"
  return lines

def files : List (String × Array String) :=
  [("qpack/insert_count_vectors.txt", insertCountLines), ("qpack/base_vectors.txt", baseLines),
    ("wire/varint_vectors.txt", varintLines), ("wire/prefixed_integer_vectors.txt", prefixedIntegerLines)]

def render (lines : Array String) : String :=
  String.intercalate "\n" lines.toList ++ "\n"

def main (args : List String) : IO UInt32 := do
  match args with
  | ["--write", directory] =>
    for (name, lines) in files do
      IO.FS.writeFile (directory ++ "/" ++ name) (render lines)
    return 0
  | ["--check", directory] =>
    let mut status : UInt32 := 0
    for (name, lines) in files do
      let path := directory ++ "/" ++ name
      let committed ← IO.FS.readFile path
      if committed != render lines then
        IO.eprintln s!"vectors: {path} differs from what spec/lean's definitions give; run `zig build lean -- write`"
        status := 1
    return status
  | _ =>
    IO.eprintln "usage: vectors (--write | --check) <src directory>"
    return 2
